import { IAIClient, AiResult } from './IAIClient';

export class MockAIClient implements IAIClient {
    async summarizeAndExtract(input: string): Promise<AiResult> {
        // Simulate latency
        await new Promise((resolve) => setTimeout(resolve, 500));

        return {
            summary: `[MOCK] Summary of input length ${input.length}: This is a simulated summary generated by the Mock AI provider. It represents the key points extracted from the provided text.`,
            tasks: [
                '[MOCK] Action Item 1: Review the input text',
                '[MOCK] Action Item 2: Validate the summary correctness',
                '[MOCK] Action Item 3: Deploy to production',
            ],
            usage: {
                promptTokens: input.length / 4,
                completionTokens: 50,
                totalTokens: (input.length / 4) + 50,
            },
        };
    }
}
